backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img" # Cartella per i file caricati dagli utenti
public_folder: "img"

collections: # Lista delle collezioni che il CMS può modificare
  - name: "property"
    label: "Proprietà"
    folder: "site/content/property"
    path: "{{slug}}/index"
    create: true
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Località", name: "location", widget: "string"}
      - {label: "Immagine Principale", name: "image", widget: "image"}
      - {label: "Prezzo", name: "price", widget: "string", hint: "es. €100/notte o €700/settimana"}
      - {label: "Camere da Letto", name: "bedrooms", widget: "number"}
      - {label: "Bagni", name: "bathrooms", widget: "number"}
      - {label: "Ospiti Massimi", name: "max_guests", widget: "number"}
      - {label: "In Evidenza sulla Homepage", name: "featured", widget: "boolean", default: false, hint: "Seleziona per mostrare questa proprietà in homepage"}
      - {label: "Breve Descrizione", name: "description", widget: "text"}
      - label: "Servizi"
        name: "amenities"
        widget: "list"
        field: {label: Servizio, name: amenity, widget: string}
      - label: "Galleria"
        name: "gallery"
        widget: "list"
        fields:
          - {label: "Immagine", name: "image", widget: "image"}
          - {label: "Testo Alternativo", name: "alt", widget: "string"}
      - {label: "Contenuto", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pagine"
    files:
      - file: "site/content/_index.md"
        label: "Homepage"
        name: "home"
        fields:
          - {label: "Titolo", name: title, widget: string}
          - {label: "Sottotitolo", name: subtitle, widget: string}
          - {label: "Immagine", name: image, widget: image}
          - {label: "Introduzione", name: intro, widget: object, fields: [
              {label: "Titolo", name: "heading", widget: string},
              {label: "Testo", name: "text", widget: "text"}
            ]}
      - file: "site/content/contact/_index.md"
        label: "Pagina Contatti"
        name: "contact"
        fields:
          - {label: "Titolo", name: title, widget: string}
          - {label: "Contenuto", name: body, widget: markdown}
          - label: "Informazioni di Contatto"
            name: contact_entries
            widget: list
            fields:
              - label: "Titolo"
                name: heading
                widget: string
              - label: "Testo"
                name: text
                widget: text
      - file: "site/content/properties/_index.md"
        label: "Pagina Proprietà"
        name: "properties"
        fields:
          - {label: "Titolo", name: title, widget: string}
          - {label: "Immagine", name: image, widget: image}
          - {label: "Introduzione", name: intro, widget: object, fields: [{label: "Titolo", name: heading, widget: string}, {label: "Descrizione", name: description, widget: text}]}
  - name: "site_settings"
    label: "Impostazioni Sito"
    files:
      - file: "site/data/contact_info.json"
        label: "Informazioni di Contatto"
        name: "contact_info"
        fields:
          - {label: "Telefono", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Slogan", name: "tagline", widget: "string"}
          - label: "Social Media"
            name: "social"
            widget: "object"
            fields:
              - {label: "Facebook Link", name: "facebook", widget: "string"}
              - {label: "Instagram Link", name: "instagram", widget: "string"}
      - file: "site/hugo.toml"
        label: "Configurazione Hugo"
        name: config
        editor:
          preview: false
        fields:
          - {label: "Titolo del Sito nel Browser", name: title, widget: string}
          - label: "Parametri"
            name: params
            widget: object
            fields:
              - label: "Immagine Open Graph"
                name: images
                widget: list
                field: { label: "Immagine", name: image, widget: image }
